import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { BiUserPlus } from 'react-icons/bi'
import Table from '../components/table'
import Form from '../components/form'
import { useState } from 'react'

export default function Home() {
  const [visible, setVisible] = useState(false);

  const handler = () => {
    setVisible(!visible)
  }

  return (
    <section>
      <Head>
        <title>GOT Management</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='https://freepngimg.com/save/87074-winter-thrones-of-is-stark-label-game/512x512' />
      </Head>
      <main className='py-5'>
        <h1 className='text-xl md:text-5xl text-center font-bold py-10'>Cast Management</h1>

        <div className="container mx-auto flex justify-between py-5 border-b">
          <div className="left flex gap-3">
            <button onClick={handler} className='flex bg-indigo-500 text-white px-4 py-2 border rounded-md hover:bg-grary-50 hover:border-indigo-500 hover:text-gray-800'>
              Add character <span className='px-1'><BiUserPlus size={23}/></span>
            </button>
          </div>
        </div>
        <div className="container mx-auto py-5">
          {visible ? <Form/> : <></>}
        </div>
        <div className="container mx-auto">
            <Table />
        </div>        
      </main>

    </section>
  )
}
